services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:80
    working_dir: /app
    depends_on:
      - database
    command: sh -c "
      composer install --ignore-platform-req=ext-gd && php artisan serve --host=0.0.0.0 --port=80
     "
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quran_forum_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
